export default function Disclaimer() {
    return (
        <div>
            <h2 className="text-xl font-bold mb-6 text-gray-800">Disclaimer</h2>

            <div className="space-y-4">
                <section>
                    <h3 className="text-lg font-semibold mb-2 text-gray-700">Educational Purpose Only</h3>
                    <p className="text-gray-600">
                        Reports and content generated by PathPR.ca are provided strictly for educational and informational purposes. They are not intended as, nor should they be used as, legal or immigration advice.
                    </p>
                </section>

                <section>
                    <h3 className="text-lg font-semibold mb-2 text-gray-700">No Immigration Consulting</h3>
                    <p className="text-gray-600">
                        PathPR.ca is not a registered immigration consultancy and does not provide immigration consultation or application submission services. For professional advice and services, users must consult licensed immigration professionals or legal representatives.
                    </p>
                </section>

                <section>
                    <h3 className="text-lg font-semibold mb-2 text-gray-700">Accuracy and Updates</h3>
                    <p className="text-gray-600">
                        While we strive to provide current and accurate information based on official Canadian immigration sources, immigration laws, policies, and criteria frequently change. We cannot guarantee absolute accuracy or completeness at all times.
                    </p>
                </section>

                <section>
                    <h3 className="text-lg font-semibold mb-2 text-gray-700">Third-party Consultants</h3>
                    <p className="text-gray-600">
                        In future phases, PathPR.ca may list licensed immigration consultants for user convenience. However, interactions with these consultants are entirely independent of PathPR.ca, and we bear no responsibility for any engagements or outcomes arising from these interactions.
                    </p>
                </section>

                <section>
                    <h3 className="text-lg font-semibold mb-2 text-gray-700">Liability</h3>
                    <p className="text-gray-600">
                        PathPR.ca holds no liability for any actions, outcomes, or decisions made by users based on the content provided.
                    </p>
                </section>
            </div>
        </div>
    );
}
