import FaqItem from './FaqItem';

export default function FAQ() {
    return (
        <div>
            <h2 className="text-xl font-bold mb-6 text-gray-800">Frequently Asked Questions</h2>

            <div className="space-y-6">
                {faqs.map((faq, index) => (
                    <FaqItem key={index} question={faq.question} answer={faq.answer} />
                ))}
            </div>
        </div>
    );
}


// FAQ Data
const faqs = [
    {
        question: "What is PathPR.ca and how can it assist me?",
        answer: "PathPR.ca is a platform designed to help individuals explore potential pathways to Canadian permanent residency (PR). By submitting your information, the website generates a personalized report outlining the PR programs you may be eligible for, streamlining your immigration planning process."
    },
    {
        question: "What information is required to generate my personalized immigration report?",
        answer: "We require details about your age, educational background, work experience, language proficiency (IELTS, CELPIP, TEF), family details, Canadian connections (relatives, previous Canadian work or study), and job offers (if any)."
    },
    {
        question: "How accurate are the immigration pathway reports generated by PathPR.ca?",
        answer: "Our reports are based on current immigration rules and eligibility criteria provided by IRCC and provincial immigration authorities. While we ensure accuracy, immigration policies can change. We recommend consulting directly with immigration professionals to confirm eligibility."
    },
    {
        question: "Can I update or modify my information after the report is generated?",
        answer: "Yes, you can log into your PathPR.ca account and update your details. A new report reflecting updated eligibility will then be generated automatically."
    },
    {
        question: "Does PathPR.ca guarantee my approval for Canadian Permanent Residency?",
        answer: "While PathPR.ca provides a clear analysis of potential PR pathways based on your profile, approval for immigration is exclusively determined by Canadian immigration authorities. Our service enhances your understanding and planning but cannot guarantee outcomes."
    },
    {
        question: "How secure is my personal information submitted on PathPR.ca?",
        answer: "We use industry-standard encryption and security measures to protect your data. Your personal information is confidential, never shared without your explicit consent, and used solely for generating your immigration report."
    },
    {
        question: "What are the main immigration pathways to Canada?",
        answer: "Canada offers several immigration programs, including: Express Entry (for skilled workers under the Federal Skilled Worker Program, Canadian Experience Class, and Federal Skilled Trades Program), Provincial Nominee Program (PNP), Family Sponsorship, Business Immigration, and Refugee and Humanitarian Programs."
    },
    {
        question: "How does Express Entry work?",
        answer: "Express Entry is a points-based system that manages applications for permanent residence. Candidates are ranked based on factors like age, education, work experience, and language proficiency. The highest-ranking candidates receive Invitations to Apply (ITAs) during periodic draws."
    },
    {
        question: "How can I check the status of my immigration application?",
        answer: "You can check your application status through the IRCC online portal. After submitting your application, you'll receive an application number, which you can use to track progress. Ensure your contact information is up-to-date to receive timely updates."
    }
];