export default function Terms() {
    return (
        <div>
            <h2 className="text-xl font-bold mb-6 text-gray-800">Terms of Service</h2>

            <div className="space-y-4">
                <section>
                    <h3 className="text-lg font-semibold mb-2 text-gray-700">Introduction</h3>
                    <p className="text-gray-600">
                        By accessing PathPR.ca, you agree to comply with these Terms of Service. This platform provides educational content through AI-generated reports related to potential Canadian immigration pathways.
                    </p>
                </section>

                <section>
                    <h3 className="text-lg font-semibold mb-2 text-gray-700">Intended Use</h3>
                    <p className="text-gray-600">
                        The content and reports generated by PathPR.ca are intended exclusively for educational purposes. PathPR.ca does not offer immigration consulting services, legal advice, or direct assistance with immigration applications.
                    </p>
                </section>

                <section>
                    <h3 className="text-lg font-semibold mb-2 text-gray-700">User Responsibilities</h3>
                    <p className="text-gray-600">
                        Users agree to provide truthful and accurate information to ensure report accuracy. Misrepresentation may result in inaccurate assessments.
                    </p>
                </section>

                <section>
                    <h3 className="text-lg font-semibold mb-2 text-gray-700">Limitations</h3>
                    <p className="text-gray-600">
                        PathPR.ca is not liable for decisions users make based on generated reports. Immigration eligibility is determined solely by Canadian immigration authorities.
                    </p>
                </section>

                <section>
                    <h3 className="text-lg font-semibold mb-2 text-gray-700">Modification of Terms</h3>
                    <p className="text-gray-600">
                        We reserve the right to modify these Terms of Service at any time, and it is the responsibility of users to regularly review them.
                    </p>
                </section>
            </div>
        </div>
    );
}   
